/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 03-Abr.-2023 16:57:53 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */
SET
	FOREIGN_KEY_CHECKS = 0;

/* Drop Tables */
DROP TABLE IF EXISTS `classes` CASCADE;

DROP TABLE IF EXISTS `companies` CASCADE;

DROP TABLE IF EXISTS `companies_contacts` CASCADE;

 /* DROP TABLE IF EXISTS `contacts` CASCADE;*/

DROP TABLE IF EXISTS `contacts_courses` CASCADE;

DROP TABLE IF EXISTS `courses` CASCADE;

DROP TABLE IF EXISTS `modules` CASCADE;

DROP TABLE IF EXISTS `roles` CASCADE;

DROP TABLE IF EXISTS `schools` CASCADE;

 /* DROP TABLE IF EXISTS `users` CASCADE; */

/* Create Tables */
CREATE TABLE `classes` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`description` VARCHAR(255) NULL,
	`message` TEXT NOT NULL,
	`classVideo` VARCHAR(255) NOT NULL,
	`enabled` BOOL NOT NULL,
	`moduleId` INT NOT NULL,
	CONSTRAINT `PK_classes` PRIMARY KEY (`id` ASC)
);

CREATE TABLE `companies` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`description` VARCHAR(1024) NULL,
	`createdAt` DATETIME NOT NULL,
	`enabled` BOOL NOT NULL,
	CONSTRAINT `PK_companies` PRIMARY KEY (`id` ASC)
);

CREATE TABLE `companies_contacts` (
	`companyId` INT NOT NULL,
	`contactId` INT NOT NULL,
	`createdAt` DATETIME NOT NULL,
	CONSTRAINT `PK_companies_contactas` PRIMARY KEY (`companyId` ASC, `contactId` ASC)
);

CREATE TABLE `contacts_courses` (
	`startDate` DATETIME NOT NULL,
	`courseId` INT NOT NULL,
	`contactId` INT NOT NULL
);

CREATE TABLE `courses` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`description` VARCHAR(255) NULL,
	`enabled` BOOL NOT NULL,
	`finalExam` VARCHAR(255) NULL,
	`finalProyect` VARCHAR(255) NULL,
	`schoolId` INT NOT NULL,
	CONSTRAINT `PK_courses` PRIMARY KEY (`id` ASC)
);

CREATE TABLE `modules` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`description` VARCHAR(255) NULL,
	`enabled` BOOL NOT NULL,
	`courseId` INT NOT NULL,
	CONSTRAINT `PK_modules` PRIMARY KEY (`id` ASC)
);

CREATE TABLE `roles` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`description` VARCHAR(255) NULL,
	CONSTRAINT `PK_roles` PRIMARY KEY (`id` ASC)
);

CREATE TABLE `schools` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`description` VARCHAR(255) NULL,
	`enabled` BOOL NOT NULL,
	CONSTRAINT `PK_Schools` PRIMARY KEY (`id` ASC)
);

/* Create Primary Keys, Indexes, Uniques, Checks */
ALTER TABLE
	`classes`
ADD
	INDEX `IXFK_classes_modules` (`moduleId` ASC);

ALTER TABLE
	`companies_contacts`
ADD
	INDEX `IXFK_companies_contactas_companies` (`companyId` ASC);

ALTER TABLE
	`companies_contacts`
ADD
	INDEX `IXFK_companies_contactas_contacts` (`contactId` ASC);

ALTER TABLE
	`contacts_courses`
ADD
	INDEX `IXFK_contacts_courses_contacts` (`contactId` ASC);

ALTER TABLE
	`contacts_courses`
ADD
	INDEX `IXFK_contacts_courses_courses` (`courseId` ASC);

ALTER TABLE
	`courses`
ADD
	INDEX `IXFK_courses_schools` (`schoolId` ASC);

ALTER TABLE
	`modules`
ADD
	INDEX `IXFK_modules_courses` (`courseId` ASC);

/* Create Foreign Key Constraints */
ALTER TABLE
	`classes`
ADD
	CONSTRAINT `FK_classes_modules` FOREIGN KEY (`moduleId`) REFERENCES `modules` (`id`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE
	`companies_contacts`
ADD
	CONSTRAINT `FK_companies_contactas_companies` FOREIGN KEY (`companyId`) REFERENCES `companies` (`id`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE
	`companies_contacts`
ADD
	CONSTRAINT `FK_companies_contactas_contacts` FOREIGN KEY (`contactId`) REFERENCES `contacts` (`id`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE
	`contacts_courses`
ADD
	CONSTRAINT `FK_contacts_courses_contacts` FOREIGN KEY (`contactId`) REFERENCES `contacts` (`id`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE
	`contacts_courses`
ADD
	CONSTRAINT `FK_contacts_courses_courses` FOREIGN KEY (`courseId`) REFERENCES `courses` (`id`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE
	`courses`
ADD
	CONSTRAINT `FK_courses_schools` FOREIGN KEY (`schoolId`) REFERENCES `schools` (`id`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE
	`modules`
ADD
	CONSTRAINT `FK_modules_courses` FOREIGN KEY (`courseId`) REFERENCES `courses` (`id`) ON DELETE Restrict ON UPDATE Restrict;

SET
	FOREIGN_KEY_CHECKS = 1;