/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 03-Abr.-2023 15:23:36 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `classes` CASCADE
;

DROP TABLE IF EXISTS `companies` CASCADE
;

DROP TABLE IF EXISTS `companies_contactas` CASCADE
;

DROP TABLE IF EXISTS `contacts` CASCADE
;

DROP TABLE IF EXISTS `contacts_courses` CASCADE
;

DROP TABLE IF EXISTS `courses` CASCADE
;

/* Create Tables */

CREATE TABLE `classes`
(
	`id` INT NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`description` VARCHAR(255) NULL,
	`message` TEXT NOT NULL,
	`classVideo` VARCHAR(255) NOT NULL,
	`enabled` BOOL NOT NULL,
	CONSTRAINT `PK_classes` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `companies`
(
	`id` INT NOT NULL,
	`name` VARCHAR(255) NOT NULL,
	`description` VARCHAR(1024) NULL,
	`createdAt` DATETIME NOT NULL,
	`enabled` BOOL NOT NULL,
	CONSTRAINT `PK_companies` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `companies_contactas`
(
	`companyId` INT NOT NULL,
	`contactId` INT NOT NULL,
	`createdAt` DATETIME NOT NULL,
	CONSTRAINT `PK_companies_contactas` PRIMARY KEY (`companyId` ASC, `contactId` ASC)
)

;

CREATE TABLE `contacts`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`number` VARCHAR(255) NOT NULL,
	`profilePicUrl` VARCHAR(255) NULL,
	`createdAt` DATETIME NOT NULL,
	`updatedAt` DATETIME NOT NULL,
	`email` VARCHAR(255) NOT NULL DEFAULT '',
	`isGroup` TINYINT NOT NULL DEFAULT 0,
	`enabled` BOOL NULL,
	CONSTRAINT `PK_contacts` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8mb4
COLLATE utf8mb4_bin

;

CREATE TABLE `contacts_courses`
(
	`id` INT NOT NULL,
	`startDate` DATETIME NOT NULL,
	`courseId` INT NOT NULL,
	`contactId` INT NOT NULL
)

;

CREATE TABLE `courses`
(
	`id` INT NOT NULL,
	`name` VARCHAR(10) NOT NULL,
	`description` VARCHAR(255) NULL,
	`enabled` BOOL NOT NULL,
	`finalExam` VARCHAR(255) NULL,
	`finalProyect` VARCHAR(255) NULL,
	CONSTRAINT `PK_courses` PRIMARY KEY (`id` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `classes` 
 ADD INDEX `IXFK_classes_courses` (`id` ASC)
;

ALTER TABLE `classes` 
 ADD INDEX `IXFK_classes_modules` (`id` ASC)
;

ALTER TABLE `companies_contactas` 
 ADD INDEX `IXFK_companies_contactas_companies` (`companyId` ASC)
;

ALTER TABLE `companies_contactas` 
 ADD INDEX `IXFK_companies_contactas_contacts` (`contactId` ASC)
;

ALTER TABLE `contacts` 
 ADD CONSTRAINT `number` UNIQUE (`number` ASC)
;

ALTER TABLE `contacts_courses` 
 ADD INDEX `IXFK_contacts_courses_contacts` (`contactId` ASC)
;

ALTER TABLE `contacts_courses` 
 ADD INDEX `IXFK_contacts_courses_courses` (`courseId` ASC)
;

ALTER TABLE `courses` 
 ADD INDEX `schoolId` (`id` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `classes` 
 ADD CONSTRAINT `FK_classes_modules`
	FOREIGN KEY (`id`) REFERENCES `modules` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `companies_contactas` 
 ADD CONSTRAINT `FK_companies_contactas_companies`
	FOREIGN KEY (`companyId`) REFERENCES `companies` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `companies_contactas` 
 ADD CONSTRAINT `FK_companies_contactas_contacts`
	FOREIGN KEY (`contactId`) REFERENCES `contacts` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `contacts_courses` 
 ADD CONSTRAINT `FK_contacts_courses_contacts`
	FOREIGN KEY (`contactId`) REFERENCES `contacts` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `contacts_courses` 
 ADD CONSTRAINT `FK_contacts_courses_courses`
	FOREIGN KEY (`courseId`) REFERENCES `courses` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `courses` 
 ADD CONSTRAINT `FK_courses_Schools`
	FOREIGN KEY (`id`) REFERENCES `schools` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 
